version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartshop_postgres
    environment:
      POSTGRES_DB: smartshop_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartshop_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  smartshop_network:
    driver: bridge