spring.application.name=smartshop
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5444/smartshop_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jackson.serialization.fail-on-empty-beans=false

# VAT Configuration
app.vat.rate=0.20


# Session Configuration
server.servlet.session.timeout=30m
server.servlet.session.cookie.name=SMARTSHOP_SESSION
server.servlet.session.cookie.http-only=true


# Swagger UI path (for you to view in browser)
springdoc.swagger-ui.path=/swagger-ui.html

# The JSON API Docs path (This is what Postman needs)
springdoc.api-docs.path=/v3/api-docs

# Optional: Sorts endpoints alphabetically
springdoc.swagger-ui.operations-sorter=alpha